### ISSUE TITLE
Windows don't float

### ISSUE THREAD

**Issue by gsingh93** [nicklan/i3config#3]
When opening windows like `yad`, the window opens and tiles in the window manager instead of floating above the status bar. How did you get it to float?

**Comment by nicklan** [comment]
Yeah, you need to add the following to your i3 config file:

```
for_window [class="YADWIN"] border none
for_window [class="YADWIN"] floating enable
```

which will cause those windows to float.  I'm gonna try and write out some more explicit instructions in the nearish future which should cover this.
